### ISSUE TITLE
Splash-Screen: Bild auf Loadingbild umstellen

### ISSUE THREAD

**Issue by pongo710** [pongo710/sopa#26]
Im Ladebildschirm der App soll nicht mehr der Couchstudio-Screen erscheinen, sondern der Sopa-Screen, der sonst auch immer beim wechseln von Screens erscheint.

**Comment by ubuntius** [comment]
Was hat dass zu bedeuten?

**Comment by pongo710** [comment]
Habe den ersten Post angepasst.
