### ISSUE TITLE
Credit-Szene

### ISSUE THREAD

**Issue by pongo710** [pongo710/sopa#29]
Für die in der App benutzten Komponenten von dritten soll es eine Szene in der App geben, in der diese gelistet sind.

**Comment by ubuntius** [comment]
http://opengameart.org/content/play-pause-mute-and-unmute-buttons

**Comment by ubuntius** [comment]
http://opengameart.org/content/menu-or-level-select-theme

**Comment by ubuntius** [comment]
http://de.clipartlogo.com/image/estrella-clip-art_457240.html

**Comment by pongo710** [comment]
Credit-Szene wurde erstellt und mit dem letzten Menüeintrag im Hauptmenü verknüpft.

Der Menüpunkt muss jetzt noch von Settings in Credits unbenannt werden.
