### ISSUE TITLE
Funktionsgrafik erstellen

### ISSUE THREAD

**Issue by pongo710** [pongo710/sopa#30]
Für den Google Play Store muss eine Funktionsgrafik erstellt werden.

Sie dient der Darstellung im Store: https://support.google.com/googleplay/android-developer/answer/1078870?hl=de

Anforderungen:
1024x500
24 Bit PNG ohne Alpha

**Comment by ubuntius** [comment]
Wurde erstellt und liegt in pr/infoBild.png

**Comment by pongo710** [comment]
Bild hat falsche Größe und muss angepasst werden.
