### ISSUE TITLE
ScoreScreen zeigt die beste Sternenanzahl an

### ISSUE THREAD

**Issue by ubuntius** [pongo710/sopa#33]
Der ScoreScreen sollte die aktuell erreichte Sternenanzahl anzeigen, nicht den Highscore

**Comment by pongo710** [comment]
Ich dachte erst, das es okay wäre den insgesamt besten Stand anzuzeigen, aber es ist ja das Ergebnis des eben gespielten Levels. Also macht es Sinn die eben erreichten Sterne anzuzeigen. Ich mach mich mal dran.
